version: '3'
services:

  mongo:
    image: mongo
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on: 
      - mongo
    logging:
      driver: none

  api: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      PORT: 3000
    volumes:
      - D:\projects\my\task-payment-api\src:/app/src
    restart: always

