module.exports = {
    ERR_UNAUTHORIZED: "ERR_UNATHORIZED",
    ERR_AUTH_TOKEN_EXPIRED: "ERR_AUTH_TOKEN_EXPIRED",
    ERR_VALIDATION: "ERR_VALIDATION",
    ERR_CANNOT_APPROVE: "ERR_CANNOT_APPROVE",
    ERR_CANNOT_CANCEL: "ERR_CANNOT_CANCEL",
    ERR_NOT_FOUND: "ERR_NOT_FOUND"
};